//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1demka.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int commentID { get; set; }
        public int messageID { get; set; }
        public int masterID { get; set; }
        public int requestID { get; set; }
    
        public virtual Master Master { get; set; }
        public virtual message message { get; set; }
    }
}
