//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1demka.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class traintryEntities : DbContext
    {
        public traintryEntities()
            : base("name=traintryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<climateTechType> climateTechType { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<request> request { get; set; }
        public virtual DbSet<requestStatus> requestStatus { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
