//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1demka.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public byte requestID { get; set; }
        public System.DateTime startDate { get; set; }
        public int climateTechTypeID { get; set; }
        public string climateTechModel { get; set; }
        public string problemDescryption { get; set; }
        public int requestStatusID { get; set; }
        public string completionDate { get; set; }
        public string repairParts { get; set; }
        public Nullable<int> masterID { get; set; }
        public int clientID { get; set; }
    
        public virtual climateTechType climateTechType { get; set; }
        public virtual Master Master { get; set; }
        public virtual requestStatus requestStatus { get; set; }
    }
}
